// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

public enum AcademyMessageTypes : int
{
  None = 0,
  Text = 1,
  Image = 2,
};


}



