// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Schale.Crypto;
using global::Google.FlatBuffers;

public struct AddressableWhiteListExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static AddressableWhiteListExcel GetRootAsAddressableWhiteListExcel(ByteBuffer _bb) { return GetRootAsAddressableWhiteListExcel(_bb, new AddressableWhiteListExcel()); }
  public static AddressableWhiteListExcel GetRootAsAddressableWhiteListExcel(ByteBuffer _bb, AddressableWhiteListExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AddressableWhiteListExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string FolderPath(int j) { int o = __p.__offset(6); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int FolderPathLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public string ResourcePath(int j) { int o = __p.__offset(8); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int ResourcePathLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Schale.FlatData.AddressableWhiteListExcel> CreateAddressableWhiteListExcel(FlatBufferBuilder builder,
      long Id = 0,
      VectorOffset folderPathOffset = default(VectorOffset),
      VectorOffset resourcePathOffset = default(VectorOffset)) {
    builder.StartTable(3);
    AddressableWhiteListExcel.AddId(builder, Id);
    AddressableWhiteListExcel.AddResourcePath(builder, resourcePathOffset);
    AddressableWhiteListExcel.AddFolderPath(builder, folderPathOffset);
    return AddressableWhiteListExcel.EndAddressableWhiteListExcel(builder);
  }

  public static void StartAddressableWhiteListExcel(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, long id) { builder.AddLong(0, id, 0); }
  public static void AddFolderPath(FlatBufferBuilder builder, VectorOffset folderPathOffset) { builder.AddOffset(1, folderPathOffset.Value, 0); }
  public static VectorOffset CreateFolderPathVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateFolderPathVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFolderPathVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFolderPathVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartFolderPathVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddResourcePath(FlatBufferBuilder builder, VectorOffset resourcePathOffset) { builder.AddOffset(2, resourcePathOffset.Value, 0); }
  public static VectorOffset CreateResourcePathVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateResourcePathVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateResourcePathVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateResourcePathVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartResourcePathVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Schale.FlatData.AddressableWhiteListExcel> EndAddressableWhiteListExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Schale.FlatData.AddressableWhiteListExcel>(o);
  }
  public AddressableWhiteListExcelT UnPack() {
    var _o = new AddressableWhiteListExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(AddressableWhiteListExcelT _o) {
		byte[] key = TableEncryptionService.CreateKey("AddressableWhiteList");
    _o.Id = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.Id, key) : this.Id;
    _o.FolderPath = new List<string>();
    for (var _j = 0; _j < this.FolderPathLength; ++_j) {_o.FolderPath.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.FolderPath(_j), key) : this.FolderPath(_j));}
    _o.ResourcePath = new List<string>();
    for (var _j = 0; _j < this.ResourcePathLength; ++_j) {_o.ResourcePath.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.ResourcePath(_j), key) : this.ResourcePath(_j));}
  }
  public static Offset<Schale.FlatData.AddressableWhiteListExcel> Pack(FlatBufferBuilder builder, AddressableWhiteListExcelT _o) {
    if (_o == null) return default(Offset<Schale.FlatData.AddressableWhiteListExcel>);
    var _folderPath = default(VectorOffset);
    if (_o.FolderPath != null) {
      var __folderPath = new StringOffset[_o.FolderPath.Count];
      for (var _j = 0; _j < __folderPath.Length; ++_j) { __folderPath[_j] = builder.CreateString(_o.FolderPath[_j]); }
      _folderPath = CreateFolderPathVector(builder, __folderPath);
    }
    var _resourcePath = default(VectorOffset);
    if (_o.ResourcePath != null) {
      var __resourcePath = new StringOffset[_o.ResourcePath.Count];
      for (var _j = 0; _j < __resourcePath.Length; ++_j) { __resourcePath[_j] = builder.CreateString(_o.ResourcePath[_j]); }
      _resourcePath = CreateResourcePathVector(builder, __resourcePath);
    }
    return CreateAddressableWhiteListExcel(
      builder,
      _o.Id,
      _folderPath,
      _resourcePath);
  }
}

public class AddressableWhiteListExcelT
{
  public long Id { get; set; }
  public List<string> FolderPath { get; set; }
  public List<string> ResourcePath { get; set; }

  public AddressableWhiteListExcelT() {
    this.Id = 0;
    this.FolderPath = null;
    this.ResourcePath = null;
  }
}


static public class AddressableWhiteListExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*long*/, 8, false)
      && verifier.VerifyVectorOfStrings(tablePos, 6 /*FolderPath*/, false)
      && verifier.VerifyVectorOfStrings(tablePos, 8 /*ResourcePath*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}



