// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

public enum BattleDialogType : int
{
  Talk = 0,
  Think = 1,
  Shout = 2,
};


}



