// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Schale.Crypto;
using global::Google.FlatBuffers;

public struct ContentTargetGroupExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ContentTargetGroupExcel GetRootAsContentTargetGroupExcel(ByteBuffer _bb) { return GetRootAsContentTargetGroupExcel(_bb, new ContentTargetGroupExcel()); }
  public static ContentTargetGroupExcel GetRootAsContentTargetGroupExcel(ByteBuffer _bb, ContentTargetGroupExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ContentTargetGroupExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Schale.FlatData.TargetGroup TargetGroup { get { int o = __p.__offset(4); return o != 0 ? (Schale.FlatData.TargetGroup)__p.bb.GetInt(o + __p.bb_pos) : Schale.FlatData.TargetGroup.WaitingSignIn; } }
  public Schale.FlatData.AccountState AccountType(int j) { int o = __p.__offset(6); return o != 0 ? (Schale.FlatData.AccountState)__p.bb.GetInt(__p.__vector(o) + j * 4) : (Schale.FlatData.AccountState)0; }
  public int AccountTypeLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<Schale.FlatData.AccountState> GetAccountTypeBytes() { return __p.__vector_as_span<Schale.FlatData.AccountState>(6, 4); }
#else
  public ArraySegment<byte>? GetAccountTypeBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public Schale.FlatData.AccountState[] GetAccountTypeArray() { int o = __p.__offset(6); if (o == 0) return null; int p = __p.__vector(o); int l = __p.__vector_len(o); Schale.FlatData.AccountState[] a = new Schale.FlatData.AccountState[l]; for (int i = 0; i < l; i++) { a[i] = (Schale.FlatData.AccountState)__p.bb.GetInt(p + i * 4); } return a; }

  public static Offset<Schale.FlatData.ContentTargetGroupExcel> CreateContentTargetGroupExcel(FlatBufferBuilder builder,
      Schale.FlatData.TargetGroup TargetGroup = Schale.FlatData.TargetGroup.WaitingSignIn,
      VectorOffset AccountTypeOffset = default(VectorOffset)) {
    builder.StartTable(2);
    ContentTargetGroupExcel.AddAccountType(builder, AccountTypeOffset);
    ContentTargetGroupExcel.AddTargetGroup(builder, TargetGroup);
    return ContentTargetGroupExcel.EndContentTargetGroupExcel(builder);
  }

  public static void StartContentTargetGroupExcel(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddTargetGroup(FlatBufferBuilder builder, Schale.FlatData.TargetGroup targetGroup) { builder.AddInt(0, (int)targetGroup, 0); }
  public static void AddAccountType(FlatBufferBuilder builder, VectorOffset accountTypeOffset) { builder.AddOffset(1, accountTypeOffset.Value, 0); }
  public static VectorOffset CreateAccountTypeVector(FlatBufferBuilder builder, Schale.FlatData.AccountState[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt((int)data[i]); return builder.EndVector(); }
  public static VectorOffset CreateAccountTypeVectorBlock(FlatBufferBuilder builder, Schale.FlatData.AccountState[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateAccountTypeVectorBlock(FlatBufferBuilder builder, ArraySegment<Schale.FlatData.AccountState> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateAccountTypeVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Schale.FlatData.AccountState>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartAccountTypeVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Schale.FlatData.ContentTargetGroupExcel> EndContentTargetGroupExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Schale.FlatData.ContentTargetGroupExcel>(o);
  }
  public ContentTargetGroupExcelT UnPack() {
    var _o = new ContentTargetGroupExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ContentTargetGroupExcelT _o) {
		byte[] key = TableEncryptionService.CreateKey("ContentTargetGroup");
    _o.TargetGroup = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.TargetGroup, key) : this.TargetGroup;
    _o.AccountType = new List<Schale.FlatData.AccountState>();
    for (var _j = 0; _j < this.AccountTypeLength; ++_j) {_o.AccountType.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.AccountType(_j), key) : this.AccountType(_j));}
  }
  public static Offset<Schale.FlatData.ContentTargetGroupExcel> Pack(FlatBufferBuilder builder, ContentTargetGroupExcelT _o) {
    if (_o == null) return default(Offset<Schale.FlatData.ContentTargetGroupExcel>);
    var _AccountType = default(VectorOffset);
    if (_o.AccountType != null) {
      var __AccountType = _o.AccountType.ToArray();
      _AccountType = CreateAccountTypeVector(builder, __AccountType);
    }
    return CreateContentTargetGroupExcel(
      builder,
      _o.TargetGroup,
      _AccountType);
  }
}

public class ContentTargetGroupExcelT
{
  public Schale.FlatData.TargetGroup TargetGroup { get; set; }
  public List<Schale.FlatData.AccountState> AccountType { get; set; }

  public ContentTargetGroupExcelT() {
    this.TargetGroup = Schale.FlatData.TargetGroup.WaitingSignIn;
    this.AccountType = null;
  }
}


static public class ContentTargetGroupExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*TargetGroup*/, 4 /*Schale.FlatData.TargetGroup*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*AccountType*/, 4 /*Schale.FlatData.AccountState*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}



