// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Schale.Crypto;
using global::Google.FlatBuffers;

public struct EventContentChangeExcelTable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static EventContentChangeExcelTable GetRootAsEventContentChangeExcelTable(ByteBuffer _bb) { return GetRootAsEventContentChangeExcelTable(_bb, new EventContentChangeExcelTable()); }
  public static EventContentChangeExcelTable GetRootAsEventContentChangeExcelTable(ByteBuffer _bb, EventContentChangeExcelTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EventContentChangeExcelTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Schale.FlatData.EventContentChangeExcel? DataList(int j) { int o = __p.__offset(4); return o != 0 ? (Schale.FlatData.EventContentChangeExcel?)(new Schale.FlatData.EventContentChangeExcel()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DataListLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Schale.FlatData.EventContentChangeExcelTable> CreateEventContentChangeExcelTable(FlatBufferBuilder builder,
      VectorOffset DataListOffset = default(VectorOffset)) {
    builder.StartTable(1);
    EventContentChangeExcelTable.AddDataList(builder, DataListOffset);
    return EventContentChangeExcelTable.EndEventContentChangeExcelTable(builder);
  }

  public static void StartEventContentChangeExcelTable(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDataList(FlatBufferBuilder builder, VectorOffset dataListOffset) { builder.AddOffset(0, dataListOffset.Value, 0); }
  public static VectorOffset CreateDataListVector(FlatBufferBuilder builder, Offset<Schale.FlatData.EventContentChangeExcel>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDataListVectorBlock(FlatBufferBuilder builder, Offset<Schale.FlatData.EventContentChangeExcel>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataListVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Schale.FlatData.EventContentChangeExcel>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataListVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Schale.FlatData.EventContentChangeExcel>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataListVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Schale.FlatData.EventContentChangeExcelTable> EndEventContentChangeExcelTable(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Schale.FlatData.EventContentChangeExcelTable>(o);
  }
  public EventContentChangeExcelTableT UnPack() {
    var _o = new EventContentChangeExcelTableT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EventContentChangeExcelTableT _o) {
		byte[] key = TableEncryptionService.CreateKey("EventContentChangeExcel");
    _o.DataList = new List<Schale.FlatData.EventContentChangeExcelT>();
    for (var _j = 0; _j < this.DataListLength; ++_j) {_o.DataList.Add(this.DataList(_j).HasValue ? this.DataList(_j).Value.UnPack() : null);}
  }
  public static Offset<Schale.FlatData.EventContentChangeExcelTable> Pack(FlatBufferBuilder builder, EventContentChangeExcelTableT _o) {
    if (_o == null) return default(Offset<Schale.FlatData.EventContentChangeExcelTable>);
    var _DataList = default(VectorOffset);
    if (_o.DataList != null) {
      var __DataList = new Offset<Schale.FlatData.EventContentChangeExcel>[_o.DataList.Count];
      for (var _j = 0; _j < __DataList.Length; ++_j) { __DataList[_j] = Schale.FlatData.EventContentChangeExcel.Pack(builder, _o.DataList[_j]); }
      _DataList = CreateDataListVector(builder, __DataList);
    }
    return CreateEventContentChangeExcelTable(
      builder,
      _DataList);
  }
}

public class EventContentChangeExcelTableT
{
  public List<Schale.FlatData.EventContentChangeExcelT> DataList { get; set; }

  public EventContentChangeExcelTableT() {
    this.DataList = null;
  }
}


static public class EventContentChangeExcelTableVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*DataList*/, Schale.FlatData.EventContentChangeExcelVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}



