// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Schale.Crypto;
using global::Google.FlatBuffers;

public struct GooglePlayAchievementExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static GooglePlayAchievementExcel GetRootAsGooglePlayAchievementExcel(ByteBuffer _bb) { return GetRootAsGooglePlayAchievementExcel(_bb, new GooglePlayAchievementExcel()); }
  public static GooglePlayAchievementExcel GetRootAsGooglePlayAchievementExcel(ByteBuffer _bb, GooglePlayAchievementExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GooglePlayAchievementExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public Schale.FlatData.ConditionType ConditionType { get { int o = __p.__offset(6); return o != 0 ? (Schale.FlatData.ConditionType)__p.bb.GetInt(o + __p.bb_pos) : Schale.FlatData.ConditionType.CompleteScenario; } }
  public long ConditionValue { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string GooglePlayId { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGooglePlayIdBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetGooglePlayIdBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetGooglePlayIdArray() { return __p.__vector_as_array<byte>(10); }
  public Schale.FlatData.AchievementType AchievementType { get { int o = __p.__offset(12); return o != 0 ? (Schale.FlatData.AchievementType)__p.bb.GetInt(o + __p.bb_pos) : Schale.FlatData.AchievementType.Unlock; } }

  public static Offset<Schale.FlatData.GooglePlayAchievementExcel> CreateGooglePlayAchievementExcel(FlatBufferBuilder builder,
      long Id = 0,
      Schale.FlatData.ConditionType ConditionType = Schale.FlatData.ConditionType.CompleteScenario,
      long ConditionValue = 0,
      StringOffset GooglePlayIdOffset = default(StringOffset),
      Schale.FlatData.AchievementType AchievementType = Schale.FlatData.AchievementType.Unlock) {
    builder.StartTable(5);
    GooglePlayAchievementExcel.AddConditionValue(builder, ConditionValue);
    GooglePlayAchievementExcel.AddId(builder, Id);
    GooglePlayAchievementExcel.AddAchievementType(builder, AchievementType);
    GooglePlayAchievementExcel.AddGooglePlayId(builder, GooglePlayIdOffset);
    GooglePlayAchievementExcel.AddConditionType(builder, ConditionType);
    return GooglePlayAchievementExcel.EndGooglePlayAchievementExcel(builder);
  }

  public static void StartGooglePlayAchievementExcel(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddId(FlatBufferBuilder builder, long id) { builder.AddLong(0, id, 0); }
  public static void AddConditionType(FlatBufferBuilder builder, Schale.FlatData.ConditionType conditionType) { builder.AddInt(1, (int)conditionType, 0); }
  public static void AddConditionValue(FlatBufferBuilder builder, long conditionValue) { builder.AddLong(2, conditionValue, 0); }
  public static void AddGooglePlayId(FlatBufferBuilder builder, StringOffset googlePlayIdOffset) { builder.AddOffset(3, googlePlayIdOffset.Value, 0); }
  public static void AddAchievementType(FlatBufferBuilder builder, Schale.FlatData.AchievementType achievementType) { builder.AddInt(4, (int)achievementType, 0); }
  public static Offset<Schale.FlatData.GooglePlayAchievementExcel> EndGooglePlayAchievementExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Schale.FlatData.GooglePlayAchievementExcel>(o);
  }
  public GooglePlayAchievementExcelT UnPack() {
    var _o = new GooglePlayAchievementExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(GooglePlayAchievementExcelT _o) {
		byte[] key = TableEncryptionService.CreateKey("GooglePlayAchievement");
    _o.Id = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.Id, key) : this.Id;
    _o.ConditionType = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.ConditionType, key) : this.ConditionType;
    _o.ConditionValue = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.ConditionValue, key) : this.ConditionValue;
    _o.GooglePlayId = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.GooglePlayId, key) : this.GooglePlayId;
    _o.AchievementType = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.AchievementType, key) : this.AchievementType;
  }
  public static Offset<Schale.FlatData.GooglePlayAchievementExcel> Pack(FlatBufferBuilder builder, GooglePlayAchievementExcelT _o) {
    if (_o == null) return default(Offset<Schale.FlatData.GooglePlayAchievementExcel>);
    var _GooglePlayId = _o.GooglePlayId == null ? default(StringOffset) : builder.CreateString(_o.GooglePlayId);
    return CreateGooglePlayAchievementExcel(
      builder,
      _o.Id,
      _o.ConditionType,
      _o.ConditionValue,
      _GooglePlayId,
      _o.AchievementType);
  }
}

public class GooglePlayAchievementExcelT
{
  public long Id { get; set; }
  public Schale.FlatData.ConditionType ConditionType { get; set; }
  public long ConditionValue { get; set; }
  public string GooglePlayId { get; set; }
  public Schale.FlatData.AchievementType AchievementType { get; set; }

  public GooglePlayAchievementExcelT() {
    this.Id = 0;
    this.ConditionType = Schale.FlatData.ConditionType.CompleteScenario;
    this.ConditionValue = 0;
    this.GooglePlayId = null;
    this.AchievementType = Schale.FlatData.AchievementType.Unlock;
  }
}


static public class GooglePlayAchievementExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*ConditionType*/, 4 /*Schale.FlatData.ConditionType*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*ConditionValue*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 10 /*GooglePlayId*/, false)
      && verifier.VerifyField(tablePos, 12 /*AchievementType*/, 4 /*Schale.FlatData.AchievementType*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}



