// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Schale.Crypto;
using global::Google.FlatBuffers;

public struct InteractiveWorldRaidSeasonManageExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static InteractiveWorldRaidSeasonManageExcel GetRootAsInteractiveWorldRaidSeasonManageExcel(ByteBuffer _bb) { return GetRootAsInteractiveWorldRaidSeasonManageExcel(_bb, new InteractiveWorldRaidSeasonManageExcel()); }
  public static InteractiveWorldRaidSeasonManageExcel GetRootAsInteractiveWorldRaidSeasonManageExcel(ByteBuffer _bb, InteractiveWorldRaidSeasonManageExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public InteractiveWorldRaidSeasonManageExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long SeasonId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long PhaseId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long PhaseStartCondition { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public bool IsReplaySeason { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public Schale.FlatData.CurrencyTypes EnterTicket { get { int o = __p.__offset(12); return o != 0 ? (Schale.FlatData.CurrencyTypes)__p.bb.GetInt(o + __p.bb_pos) : Schale.FlatData.CurrencyTypes.Invalid; } }
  public string PhaseStartTime { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPhaseStartTimeBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetPhaseStartTimeBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetPhaseStartTimeArray() { return __p.__vector_as_array<byte>(14); }
  public string PhaseEndTime { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPhaseEndTimeBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetPhaseEndTimeBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetPhaseEndTimeArray() { return __p.__vector_as_array<byte>(16); }
  public string WorldRaidLobbyScene { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetWorldRaidLobbySceneBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetWorldRaidLobbySceneBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetWorldRaidLobbySceneArray() { return __p.__vector_as_array<byte>(18); }
  public string WorldRaidLobbyBanner { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetWorldRaidLobbyBannerBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetWorldRaidLobbyBannerBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetWorldRaidLobbyBannerArray() { return __p.__vector_as_array<byte>(20); }
  public string WorldRaidLobbyBG { get { int o = __p.__offset(22); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetWorldRaidLobbyBGBytes() { return __p.__vector_as_span<byte>(22, 1); }
#else
  public ArraySegment<byte>? GetWorldRaidLobbyBGBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public byte[] GetWorldRaidLobbyBGArray() { return __p.__vector_as_array<byte>(22); }
  public bool WorldRaidLobbyBannerShow { get { int o = __p.__offset(24); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public long SeasonOpenCondition { get { int o = __p.__offset(26); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long WorldRaidLobbyEnterScenario { get { int o = __p.__offset(28); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public bool CanPlayNotSeasonTime { get { int o = __p.__offset(30); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool WorldRaidUniqueThemeLobbyUI { get { int o = __p.__offset(32); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string WorldRaidUniqueThemeName { get { int o = __p.__offset(34); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetWorldRaidUniqueThemeNameBytes() { return __p.__vector_as_span<byte>(34, 1); }
#else
  public ArraySegment<byte>? GetWorldRaidUniqueThemeNameBytes() { return __p.__vector_as_arraysegment(34); }
#endif
  public byte[] GetWorldRaidUniqueThemeNameArray() { return __p.__vector_as_array<byte>(34); }
  public bool CanWorldRaidGemEnter { get { int o = __p.__offset(36); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool HideWorldRaidTicketUI { get { int o = __p.__offset(38); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool HideWorldRaidBossCompleteRewardUI { get { int o = __p.__offset(40); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool UseWorldRaidCommonToast { get { int o = __p.__offset(42); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public long OpenRaidBossGroupId(int j) { int o = __p.__offset(44); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int OpenRaidBossGroupIdLength { get { int o = __p.__offset(44); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetOpenRaidBossGroupIdBytes() { return __p.__vector_as_span<long>(44, 8); }
#else
  public ArraySegment<byte>? GetOpenRaidBossGroupIdBytes() { return __p.__vector_as_arraysegment(44); }
#endif
  public long[] GetOpenRaidBossGroupIdArray() { return __p.__vector_as_array<long>(44); }
  public string BossSpawnTime(int j) { int o = __p.__offset(46); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int BossSpawnTimeLength { get { int o = __p.__offset(46); return o != 0 ? __p.__vector_len(o) : 0; } }
  public string EliminateTime(int j) { int o = __p.__offset(48); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int EliminateTimeLength { get { int o = __p.__offset(48); return o != 0 ? __p.__vector_len(o) : 0; } }
  public long ScenarioOutputConditionId(int j) { int o = __p.__offset(50); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int ScenarioOutputConditionIdLength { get { int o = __p.__offset(50); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetScenarioOutputConditionIdBytes() { return __p.__vector_as_span<long>(50, 8); }
#else
  public ArraySegment<byte>? GetScenarioOutputConditionIdBytes() { return __p.__vector_as_arraysegment(50); }
#endif
  public long[] GetScenarioOutputConditionIdArray() { return __p.__vector_as_array<long>(50); }
  public long ConditionScenarioGroupid(int j) { int o = __p.__offset(52); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int ConditionScenarioGroupidLength { get { int o = __p.__offset(52); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetConditionScenarioGroupidBytes() { return __p.__vector_as_span<long>(52, 8); }
#else
  public ArraySegment<byte>? GetConditionScenarioGroupidBytes() { return __p.__vector_as_arraysegment(52); }
#endif
  public long[] GetConditionScenarioGroupidArray() { return __p.__vector_as_array<long>(52); }
  public long CarrierSkillGroupId { get { int o = __p.__offset(54); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string WorldRaidMapEnterOperator { get { int o = __p.__offset(56); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetWorldRaidMapEnterOperatorBytes() { return __p.__vector_as_span<byte>(56, 1); }
#else
  public ArraySegment<byte>? GetWorldRaidMapEnterOperatorBytes() { return __p.__vector_as_arraysegment(56); }
#endif
  public byte[] GetWorldRaidMapEnterOperatorArray() { return __p.__vector_as_array<byte>(56); }
  public bool UseFavorRankBuff { get { int o = __p.__offset(58); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Schale.FlatData.InteractiveWorldRaidSeasonManageExcel> CreateInteractiveWorldRaidSeasonManageExcel(FlatBufferBuilder builder,
      long SeasonId = 0,
      long PhaseId = 0,
      long PhaseStartCondition = 0,
      bool IsReplaySeason = false,
      Schale.FlatData.CurrencyTypes EnterTicket = Schale.FlatData.CurrencyTypes.Invalid,
      StringOffset PhaseStartTimeOffset = default(StringOffset),
      StringOffset PhaseEndTimeOffset = default(StringOffset),
      StringOffset WorldRaidLobbySceneOffset = default(StringOffset),
      StringOffset WorldRaidLobbyBannerOffset = default(StringOffset),
      StringOffset WorldRaidLobbyBGOffset = default(StringOffset),
      bool WorldRaidLobbyBannerShow = false,
      long SeasonOpenCondition = 0,
      long WorldRaidLobbyEnterScenario = 0,
      bool CanPlayNotSeasonTime = false,
      bool WorldRaidUniqueThemeLobbyUI = false,
      StringOffset WorldRaidUniqueThemeNameOffset = default(StringOffset),
      bool CanWorldRaidGemEnter = false,
      bool HideWorldRaidTicketUI = false,
      bool HideWorldRaidBossCompleteRewardUI = false,
      bool UseWorldRaidCommonToast = false,
      VectorOffset OpenRaidBossGroupIdOffset = default(VectorOffset),
      VectorOffset BossSpawnTimeOffset = default(VectorOffset),
      VectorOffset EliminateTimeOffset = default(VectorOffset),
      VectorOffset ScenarioOutputConditionIdOffset = default(VectorOffset),
      VectorOffset ConditionScenarioGroupidOffset = default(VectorOffset),
      long CarrierSkillGroupId = 0,
      StringOffset WorldRaidMapEnterOperatorOffset = default(StringOffset),
      bool UseFavorRankBuff = false) {
    builder.StartTable(28);
    InteractiveWorldRaidSeasonManageExcel.AddCarrierSkillGroupId(builder, CarrierSkillGroupId);
    InteractiveWorldRaidSeasonManageExcel.AddWorldRaidLobbyEnterScenario(builder, WorldRaidLobbyEnterScenario);
    InteractiveWorldRaidSeasonManageExcel.AddSeasonOpenCondition(builder, SeasonOpenCondition);
    InteractiveWorldRaidSeasonManageExcel.AddPhaseStartCondition(builder, PhaseStartCondition);
    InteractiveWorldRaidSeasonManageExcel.AddPhaseId(builder, PhaseId);
    InteractiveWorldRaidSeasonManageExcel.AddSeasonId(builder, SeasonId);
    InteractiveWorldRaidSeasonManageExcel.AddWorldRaidMapEnterOperator(builder, WorldRaidMapEnterOperatorOffset);
    InteractiveWorldRaidSeasonManageExcel.AddConditionScenarioGroupid(builder, ConditionScenarioGroupidOffset);
    InteractiveWorldRaidSeasonManageExcel.AddScenarioOutputConditionId(builder, ScenarioOutputConditionIdOffset);
    InteractiveWorldRaidSeasonManageExcel.AddEliminateTime(builder, EliminateTimeOffset);
    InteractiveWorldRaidSeasonManageExcel.AddBossSpawnTime(builder, BossSpawnTimeOffset);
    InteractiveWorldRaidSeasonManageExcel.AddOpenRaidBossGroupId(builder, OpenRaidBossGroupIdOffset);
    InteractiveWorldRaidSeasonManageExcel.AddWorldRaidUniqueThemeName(builder, WorldRaidUniqueThemeNameOffset);
    InteractiveWorldRaidSeasonManageExcel.AddWorldRaidLobbyBG(builder, WorldRaidLobbyBGOffset);
    InteractiveWorldRaidSeasonManageExcel.AddWorldRaidLobbyBanner(builder, WorldRaidLobbyBannerOffset);
    InteractiveWorldRaidSeasonManageExcel.AddWorldRaidLobbyScene(builder, WorldRaidLobbySceneOffset);
    InteractiveWorldRaidSeasonManageExcel.AddPhaseEndTime(builder, PhaseEndTimeOffset);
    InteractiveWorldRaidSeasonManageExcel.AddPhaseStartTime(builder, PhaseStartTimeOffset);
    InteractiveWorldRaidSeasonManageExcel.AddEnterTicket(builder, EnterTicket);
    InteractiveWorldRaidSeasonManageExcel.AddUseFavorRankBuff(builder, UseFavorRankBuff);
    InteractiveWorldRaidSeasonManageExcel.AddUseWorldRaidCommonToast(builder, UseWorldRaidCommonToast);
    InteractiveWorldRaidSeasonManageExcel.AddHideWorldRaidBossCompleteRewardUI(builder, HideWorldRaidBossCompleteRewardUI);
    InteractiveWorldRaidSeasonManageExcel.AddHideWorldRaidTicketUI(builder, HideWorldRaidTicketUI);
    InteractiveWorldRaidSeasonManageExcel.AddCanWorldRaidGemEnter(builder, CanWorldRaidGemEnter);
    InteractiveWorldRaidSeasonManageExcel.AddWorldRaidUniqueThemeLobbyUI(builder, WorldRaidUniqueThemeLobbyUI);
    InteractiveWorldRaidSeasonManageExcel.AddCanPlayNotSeasonTime(builder, CanPlayNotSeasonTime);
    InteractiveWorldRaidSeasonManageExcel.AddWorldRaidLobbyBannerShow(builder, WorldRaidLobbyBannerShow);
    InteractiveWorldRaidSeasonManageExcel.AddIsReplaySeason(builder, IsReplaySeason);
    return InteractiveWorldRaidSeasonManageExcel.EndInteractiveWorldRaidSeasonManageExcel(builder);
  }

  public static void StartInteractiveWorldRaidSeasonManageExcel(FlatBufferBuilder builder) { builder.StartTable(28); }
  public static void AddSeasonId(FlatBufferBuilder builder, long seasonId) { builder.AddLong(0, seasonId, 0); }
  public static void AddPhaseId(FlatBufferBuilder builder, long phaseId) { builder.AddLong(1, phaseId, 0); }
  public static void AddPhaseStartCondition(FlatBufferBuilder builder, long phaseStartCondition) { builder.AddLong(2, phaseStartCondition, 0); }
  public static void AddIsReplaySeason(FlatBufferBuilder builder, bool isReplaySeason) { builder.AddBool(3, isReplaySeason, false); }
  public static void AddEnterTicket(FlatBufferBuilder builder, Schale.FlatData.CurrencyTypes enterTicket) { builder.AddInt(4, (int)enterTicket, 0); }
  public static void AddPhaseStartTime(FlatBufferBuilder builder, StringOffset phaseStartTimeOffset) { builder.AddOffset(5, phaseStartTimeOffset.Value, 0); }
  public static void AddPhaseEndTime(FlatBufferBuilder builder, StringOffset phaseEndTimeOffset) { builder.AddOffset(6, phaseEndTimeOffset.Value, 0); }
  public static void AddWorldRaidLobbyScene(FlatBufferBuilder builder, StringOffset worldRaidLobbySceneOffset) { builder.AddOffset(7, worldRaidLobbySceneOffset.Value, 0); }
  public static void AddWorldRaidLobbyBanner(FlatBufferBuilder builder, StringOffset worldRaidLobbyBannerOffset) { builder.AddOffset(8, worldRaidLobbyBannerOffset.Value, 0); }
  public static void AddWorldRaidLobbyBG(FlatBufferBuilder builder, StringOffset worldRaidLobbyBGOffset) { builder.AddOffset(9, worldRaidLobbyBGOffset.Value, 0); }
  public static void AddWorldRaidLobbyBannerShow(FlatBufferBuilder builder, bool worldRaidLobbyBannerShow) { builder.AddBool(10, worldRaidLobbyBannerShow, false); }
  public static void AddSeasonOpenCondition(FlatBufferBuilder builder, long seasonOpenCondition) { builder.AddLong(11, seasonOpenCondition, 0); }
  public static void AddWorldRaidLobbyEnterScenario(FlatBufferBuilder builder, long worldRaidLobbyEnterScenario) { builder.AddLong(12, worldRaidLobbyEnterScenario, 0); }
  public static void AddCanPlayNotSeasonTime(FlatBufferBuilder builder, bool canPlayNotSeasonTime) { builder.AddBool(13, canPlayNotSeasonTime, false); }
  public static void AddWorldRaidUniqueThemeLobbyUI(FlatBufferBuilder builder, bool worldRaidUniqueThemeLobbyUI) { builder.AddBool(14, worldRaidUniqueThemeLobbyUI, false); }
  public static void AddWorldRaidUniqueThemeName(FlatBufferBuilder builder, StringOffset worldRaidUniqueThemeNameOffset) { builder.AddOffset(15, worldRaidUniqueThemeNameOffset.Value, 0); }
  public static void AddCanWorldRaidGemEnter(FlatBufferBuilder builder, bool canWorldRaidGemEnter) { builder.AddBool(16, canWorldRaidGemEnter, false); }
  public static void AddHideWorldRaidTicketUI(FlatBufferBuilder builder, bool hideWorldRaidTicketUI) { builder.AddBool(17, hideWorldRaidTicketUI, false); }
  public static void AddHideWorldRaidBossCompleteRewardUI(FlatBufferBuilder builder, bool hideWorldRaidBossCompleteRewardUI) { builder.AddBool(18, hideWorldRaidBossCompleteRewardUI, false); }
  public static void AddUseWorldRaidCommonToast(FlatBufferBuilder builder, bool useWorldRaidCommonToast) { builder.AddBool(19, useWorldRaidCommonToast, false); }
  public static void AddOpenRaidBossGroupId(FlatBufferBuilder builder, VectorOffset openRaidBossGroupIdOffset) { builder.AddOffset(20, openRaidBossGroupIdOffset.Value, 0); }
  public static VectorOffset CreateOpenRaidBossGroupIdVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateOpenRaidBossGroupIdVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOpenRaidBossGroupIdVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOpenRaidBossGroupIdVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartOpenRaidBossGroupIdVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static void AddBossSpawnTime(FlatBufferBuilder builder, VectorOffset bossSpawnTimeOffset) { builder.AddOffset(21, bossSpawnTimeOffset.Value, 0); }
  public static VectorOffset CreateBossSpawnTimeVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateBossSpawnTimeVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBossSpawnTimeVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBossSpawnTimeVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartBossSpawnTimeVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddEliminateTime(FlatBufferBuilder builder, VectorOffset eliminateTimeOffset) { builder.AddOffset(22, eliminateTimeOffset.Value, 0); }
  public static VectorOffset CreateEliminateTimeVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateEliminateTimeVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEliminateTimeVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEliminateTimeVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEliminateTimeVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddScenarioOutputConditionId(FlatBufferBuilder builder, VectorOffset scenarioOutputConditionIdOffset) { builder.AddOffset(23, scenarioOutputConditionIdOffset.Value, 0); }
  public static VectorOffset CreateScenarioOutputConditionIdVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateScenarioOutputConditionIdVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateScenarioOutputConditionIdVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateScenarioOutputConditionIdVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartScenarioOutputConditionIdVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static void AddConditionScenarioGroupid(FlatBufferBuilder builder, VectorOffset conditionScenarioGroupidOffset) { builder.AddOffset(24, conditionScenarioGroupidOffset.Value, 0); }
  public static VectorOffset CreateConditionScenarioGroupidVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateConditionScenarioGroupidVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateConditionScenarioGroupidVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateConditionScenarioGroupidVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartConditionScenarioGroupidVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static void AddCarrierSkillGroupId(FlatBufferBuilder builder, long carrierSkillGroupId) { builder.AddLong(25, carrierSkillGroupId, 0); }
  public static void AddWorldRaidMapEnterOperator(FlatBufferBuilder builder, StringOffset worldRaidMapEnterOperatorOffset) { builder.AddOffset(26, worldRaidMapEnterOperatorOffset.Value, 0); }
  public static void AddUseFavorRankBuff(FlatBufferBuilder builder, bool useFavorRankBuff) { builder.AddBool(27, useFavorRankBuff, false); }
  public static Offset<Schale.FlatData.InteractiveWorldRaidSeasonManageExcel> EndInteractiveWorldRaidSeasonManageExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Schale.FlatData.InteractiveWorldRaidSeasonManageExcel>(o);
  }
  public InteractiveWorldRaidSeasonManageExcelT UnPack() {
    var _o = new InteractiveWorldRaidSeasonManageExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(InteractiveWorldRaidSeasonManageExcelT _o) {
		byte[] key = TableEncryptionService.CreateKey("InteractiveWorldRaidSeasonManage");
    _o.SeasonId = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.SeasonId, key) : this.SeasonId;
    _o.PhaseId = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.PhaseId, key) : this.PhaseId;
    _o.PhaseStartCondition = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.PhaseStartCondition, key) : this.PhaseStartCondition;
    _o.IsReplaySeason = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.IsReplaySeason, key) : this.IsReplaySeason;
    _o.EnterTicket = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.EnterTicket, key) : this.EnterTicket;
    _o.PhaseStartTime = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.PhaseStartTime, key) : this.PhaseStartTime;
    _o.PhaseEndTime = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.PhaseEndTime, key) : this.PhaseEndTime;
    _o.WorldRaidLobbyScene = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.WorldRaidLobbyScene, key) : this.WorldRaidLobbyScene;
    _o.WorldRaidLobbyBanner = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.WorldRaidLobbyBanner, key) : this.WorldRaidLobbyBanner;
    _o.WorldRaidLobbyBG = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.WorldRaidLobbyBG, key) : this.WorldRaidLobbyBG;
    _o.WorldRaidLobbyBannerShow = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.WorldRaidLobbyBannerShow, key) : this.WorldRaidLobbyBannerShow;
    _o.SeasonOpenCondition = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.SeasonOpenCondition, key) : this.SeasonOpenCondition;
    _o.WorldRaidLobbyEnterScenario = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.WorldRaidLobbyEnterScenario, key) : this.WorldRaidLobbyEnterScenario;
    _o.CanPlayNotSeasonTime = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.CanPlayNotSeasonTime, key) : this.CanPlayNotSeasonTime;
    _o.WorldRaidUniqueThemeLobbyUI = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.WorldRaidUniqueThemeLobbyUI, key) : this.WorldRaidUniqueThemeLobbyUI;
    _o.WorldRaidUniqueThemeName = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.WorldRaidUniqueThemeName, key) : this.WorldRaidUniqueThemeName;
    _o.CanWorldRaidGemEnter = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.CanWorldRaidGemEnter, key) : this.CanWorldRaidGemEnter;
    _o.HideWorldRaidTicketUI = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.HideWorldRaidTicketUI, key) : this.HideWorldRaidTicketUI;
    _o.HideWorldRaidBossCompleteRewardUI = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.HideWorldRaidBossCompleteRewardUI, key) : this.HideWorldRaidBossCompleteRewardUI;
    _o.UseWorldRaidCommonToast = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.UseWorldRaidCommonToast, key) : this.UseWorldRaidCommonToast;
    _o.OpenRaidBossGroupId = new List<long>();
    for (var _j = 0; _j < this.OpenRaidBossGroupIdLength; ++_j) {_o.OpenRaidBossGroupId.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.OpenRaidBossGroupId(_j), key) : this.OpenRaidBossGroupId(_j));}
    _o.BossSpawnTime = new List<string>();
    for (var _j = 0; _j < this.BossSpawnTimeLength; ++_j) {_o.BossSpawnTime.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.BossSpawnTime(_j), key) : this.BossSpawnTime(_j));}
    _o.EliminateTime = new List<string>();
    for (var _j = 0; _j < this.EliminateTimeLength; ++_j) {_o.EliminateTime.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.EliminateTime(_j), key) : this.EliminateTime(_j));}
    _o.ScenarioOutputConditionId = new List<long>();
    for (var _j = 0; _j < this.ScenarioOutputConditionIdLength; ++_j) {_o.ScenarioOutputConditionId.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.ScenarioOutputConditionId(_j), key) : this.ScenarioOutputConditionId(_j));}
    _o.ConditionScenarioGroupid = new List<long>();
    for (var _j = 0; _j < this.ConditionScenarioGroupidLength; ++_j) {_o.ConditionScenarioGroupid.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.ConditionScenarioGroupid(_j), key) : this.ConditionScenarioGroupid(_j));}
    _o.CarrierSkillGroupId = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.CarrierSkillGroupId, key) : this.CarrierSkillGroupId;
    _o.WorldRaidMapEnterOperator = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.WorldRaidMapEnterOperator, key) : this.WorldRaidMapEnterOperator;
    _o.UseFavorRankBuff = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.UseFavorRankBuff, key) : this.UseFavorRankBuff;
  }
  public static Offset<Schale.FlatData.InteractiveWorldRaidSeasonManageExcel> Pack(FlatBufferBuilder builder, InteractiveWorldRaidSeasonManageExcelT _o) {
    if (_o == null) return default(Offset<Schale.FlatData.InteractiveWorldRaidSeasonManageExcel>);
    var _PhaseStartTime = _o.PhaseStartTime == null ? default(StringOffset) : builder.CreateString(_o.PhaseStartTime);
    var _PhaseEndTime = _o.PhaseEndTime == null ? default(StringOffset) : builder.CreateString(_o.PhaseEndTime);
    var _WorldRaidLobbyScene = _o.WorldRaidLobbyScene == null ? default(StringOffset) : builder.CreateString(_o.WorldRaidLobbyScene);
    var _WorldRaidLobbyBanner = _o.WorldRaidLobbyBanner == null ? default(StringOffset) : builder.CreateString(_o.WorldRaidLobbyBanner);
    var _WorldRaidLobbyBG = _o.WorldRaidLobbyBG == null ? default(StringOffset) : builder.CreateString(_o.WorldRaidLobbyBG);
    var _WorldRaidUniqueThemeName = _o.WorldRaidUniqueThemeName == null ? default(StringOffset) : builder.CreateString(_o.WorldRaidUniqueThemeName);
    var _OpenRaidBossGroupId = default(VectorOffset);
    if (_o.OpenRaidBossGroupId != null) {
      var __OpenRaidBossGroupId = _o.OpenRaidBossGroupId.ToArray();
      _OpenRaidBossGroupId = CreateOpenRaidBossGroupIdVector(builder, __OpenRaidBossGroupId);
    }
    var _BossSpawnTime = default(VectorOffset);
    if (_o.BossSpawnTime != null) {
      var __BossSpawnTime = new StringOffset[_o.BossSpawnTime.Count];
      for (var _j = 0; _j < __BossSpawnTime.Length; ++_j) { __BossSpawnTime[_j] = builder.CreateString(_o.BossSpawnTime[_j]); }
      _BossSpawnTime = CreateBossSpawnTimeVector(builder, __BossSpawnTime);
    }
    var _EliminateTime = default(VectorOffset);
    if (_o.EliminateTime != null) {
      var __EliminateTime = new StringOffset[_o.EliminateTime.Count];
      for (var _j = 0; _j < __EliminateTime.Length; ++_j) { __EliminateTime[_j] = builder.CreateString(_o.EliminateTime[_j]); }
      _EliminateTime = CreateEliminateTimeVector(builder, __EliminateTime);
    }
    var _ScenarioOutputConditionId = default(VectorOffset);
    if (_o.ScenarioOutputConditionId != null) {
      var __ScenarioOutputConditionId = _o.ScenarioOutputConditionId.ToArray();
      _ScenarioOutputConditionId = CreateScenarioOutputConditionIdVector(builder, __ScenarioOutputConditionId);
    }
    var _ConditionScenarioGroupid = default(VectorOffset);
    if (_o.ConditionScenarioGroupid != null) {
      var __ConditionScenarioGroupid = _o.ConditionScenarioGroupid.ToArray();
      _ConditionScenarioGroupid = CreateConditionScenarioGroupidVector(builder, __ConditionScenarioGroupid);
    }
    var _WorldRaidMapEnterOperator = _o.WorldRaidMapEnterOperator == null ? default(StringOffset) : builder.CreateString(_o.WorldRaidMapEnterOperator);
    return CreateInteractiveWorldRaidSeasonManageExcel(
      builder,
      _o.SeasonId,
      _o.PhaseId,
      _o.PhaseStartCondition,
      _o.IsReplaySeason,
      _o.EnterTicket,
      _PhaseStartTime,
      _PhaseEndTime,
      _WorldRaidLobbyScene,
      _WorldRaidLobbyBanner,
      _WorldRaidLobbyBG,
      _o.WorldRaidLobbyBannerShow,
      _o.SeasonOpenCondition,
      _o.WorldRaidLobbyEnterScenario,
      _o.CanPlayNotSeasonTime,
      _o.WorldRaidUniqueThemeLobbyUI,
      _WorldRaidUniqueThemeName,
      _o.CanWorldRaidGemEnter,
      _o.HideWorldRaidTicketUI,
      _o.HideWorldRaidBossCompleteRewardUI,
      _o.UseWorldRaidCommonToast,
      _OpenRaidBossGroupId,
      _BossSpawnTime,
      _EliminateTime,
      _ScenarioOutputConditionId,
      _ConditionScenarioGroupid,
      _o.CarrierSkillGroupId,
      _WorldRaidMapEnterOperator,
      _o.UseFavorRankBuff);
  }
}

public class InteractiveWorldRaidSeasonManageExcelT
{
  public long SeasonId { get; set; }
  public long PhaseId { get; set; }
  public long PhaseStartCondition { get; set; }
  public bool IsReplaySeason { get; set; }
  public Schale.FlatData.CurrencyTypes EnterTicket { get; set; }
  public string PhaseStartTime { get; set; }
  public string PhaseEndTime { get; set; }
  public string WorldRaidLobbyScene { get; set; }
  public string WorldRaidLobbyBanner { get; set; }
  public string WorldRaidLobbyBG { get; set; }
  public bool WorldRaidLobbyBannerShow { get; set; }
  public long SeasonOpenCondition { get; set; }
  public long WorldRaidLobbyEnterScenario { get; set; }
  public bool CanPlayNotSeasonTime { get; set; }
  public bool WorldRaidUniqueThemeLobbyUI { get; set; }
  public string WorldRaidUniqueThemeName { get; set; }
  public bool CanWorldRaidGemEnter { get; set; }
  public bool HideWorldRaidTicketUI { get; set; }
  public bool HideWorldRaidBossCompleteRewardUI { get; set; }
  public bool UseWorldRaidCommonToast { get; set; }
  public List<long> OpenRaidBossGroupId { get; set; }
  public List<string> BossSpawnTime { get; set; }
  public List<string> EliminateTime { get; set; }
  public List<long> ScenarioOutputConditionId { get; set; }
  public List<long> ConditionScenarioGroupid { get; set; }
  public long CarrierSkillGroupId { get; set; }
  public string WorldRaidMapEnterOperator { get; set; }
  public bool UseFavorRankBuff { get; set; }

  public InteractiveWorldRaidSeasonManageExcelT() {
    this.SeasonId = 0;
    this.PhaseId = 0;
    this.PhaseStartCondition = 0;
    this.IsReplaySeason = false;
    this.EnterTicket = Schale.FlatData.CurrencyTypes.Invalid;
    this.PhaseStartTime = null;
    this.PhaseEndTime = null;
    this.WorldRaidLobbyScene = null;
    this.WorldRaidLobbyBanner = null;
    this.WorldRaidLobbyBG = null;
    this.WorldRaidLobbyBannerShow = false;
    this.SeasonOpenCondition = 0;
    this.WorldRaidLobbyEnterScenario = 0;
    this.CanPlayNotSeasonTime = false;
    this.WorldRaidUniqueThemeLobbyUI = false;
    this.WorldRaidUniqueThemeName = null;
    this.CanWorldRaidGemEnter = false;
    this.HideWorldRaidTicketUI = false;
    this.HideWorldRaidBossCompleteRewardUI = false;
    this.UseWorldRaidCommonToast = false;
    this.OpenRaidBossGroupId = null;
    this.BossSpawnTime = null;
    this.EliminateTime = null;
    this.ScenarioOutputConditionId = null;
    this.ConditionScenarioGroupid = null;
    this.CarrierSkillGroupId = 0;
    this.WorldRaidMapEnterOperator = null;
    this.UseFavorRankBuff = false;
  }
}


static public class InteractiveWorldRaidSeasonManageExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*SeasonId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*PhaseId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*PhaseStartCondition*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 10 /*IsReplaySeason*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 12 /*EnterTicket*/, 4 /*Schale.FlatData.CurrencyTypes*/, 4, false)
      && verifier.VerifyString(tablePos, 14 /*PhaseStartTime*/, false)
      && verifier.VerifyString(tablePos, 16 /*PhaseEndTime*/, false)
      && verifier.VerifyString(tablePos, 18 /*WorldRaidLobbyScene*/, false)
      && verifier.VerifyString(tablePos, 20 /*WorldRaidLobbyBanner*/, false)
      && verifier.VerifyString(tablePos, 22 /*WorldRaidLobbyBG*/, false)
      && verifier.VerifyField(tablePos, 24 /*WorldRaidLobbyBannerShow*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 26 /*SeasonOpenCondition*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 28 /*WorldRaidLobbyEnterScenario*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 30 /*CanPlayNotSeasonTime*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 32 /*WorldRaidUniqueThemeLobbyUI*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 34 /*WorldRaidUniqueThemeName*/, false)
      && verifier.VerifyField(tablePos, 36 /*CanWorldRaidGemEnter*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 38 /*HideWorldRaidTicketUI*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 40 /*HideWorldRaidBossCompleteRewardUI*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 42 /*UseWorldRaidCommonToast*/, 1 /*bool*/, 1, false)
      && verifier.VerifyVectorOfData(tablePos, 44 /*OpenRaidBossGroupId*/, 8 /*long*/, false)
      && verifier.VerifyVectorOfStrings(tablePos, 46 /*BossSpawnTime*/, false)
      && verifier.VerifyVectorOfStrings(tablePos, 48 /*EliminateTime*/, false)
      && verifier.VerifyVectorOfData(tablePos, 50 /*ScenarioOutputConditionId*/, 8 /*long*/, false)
      && verifier.VerifyVectorOfData(tablePos, 52 /*ConditionScenarioGroupid*/, 8 /*long*/, false)
      && verifier.VerifyField(tablePos, 54 /*CarrierSkillGroupId*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 56 /*WorldRaidMapEnterOperator*/, false)
      && verifier.VerifyField(tablePos, 58 /*UseFavorRankBuff*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}



