// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Schale.Crypto;
using global::Google.FlatBuffers;

public struct MiniGameRoadPuzzleAdditionalRewardExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MiniGameRoadPuzzleAdditionalRewardExcel GetRootAsMiniGameRoadPuzzleAdditionalRewardExcel(ByteBuffer _bb) { return GetRootAsMiniGameRoadPuzzleAdditionalRewardExcel(_bb, new MiniGameRoadPuzzleAdditionalRewardExcel()); }
  public static MiniGameRoadPuzzleAdditionalRewardExcel GetRootAsMiniGameRoadPuzzleAdditionalRewardExcel(ByteBuffer _bb, MiniGameRoadPuzzleAdditionalRewardExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MiniGameRoadPuzzleAdditionalRewardExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long EventContentId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long UniqueId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public Schale.FlatData.ParcelType RewardParcelType { get { int o = __p.__offset(8); return o != 0 ? (Schale.FlatData.ParcelType)__p.bb.GetInt(o + __p.bb_pos) : Schale.FlatData.ParcelType.None; } }
  public long RewardParcelId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long RewardParcelAmount { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Schale.FlatData.MiniGameRoadPuzzleAdditionalRewardExcel> CreateMiniGameRoadPuzzleAdditionalRewardExcel(FlatBufferBuilder builder,
      long EventContentId = 0,
      long UniqueId = 0,
      Schale.FlatData.ParcelType RewardParcelType = Schale.FlatData.ParcelType.None,
      long RewardParcelId = 0,
      long RewardParcelAmount = 0) {
    builder.StartTable(5);
    MiniGameRoadPuzzleAdditionalRewardExcel.AddRewardParcelAmount(builder, RewardParcelAmount);
    MiniGameRoadPuzzleAdditionalRewardExcel.AddRewardParcelId(builder, RewardParcelId);
    MiniGameRoadPuzzleAdditionalRewardExcel.AddUniqueId(builder, UniqueId);
    MiniGameRoadPuzzleAdditionalRewardExcel.AddEventContentId(builder, EventContentId);
    MiniGameRoadPuzzleAdditionalRewardExcel.AddRewardParcelType(builder, RewardParcelType);
    return MiniGameRoadPuzzleAdditionalRewardExcel.EndMiniGameRoadPuzzleAdditionalRewardExcel(builder);
  }

  public static void StartMiniGameRoadPuzzleAdditionalRewardExcel(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddEventContentId(FlatBufferBuilder builder, long eventContentId) { builder.AddLong(0, eventContentId, 0); }
  public static void AddUniqueId(FlatBufferBuilder builder, long uniqueId) { builder.AddLong(1, uniqueId, 0); }
  public static void AddRewardParcelType(FlatBufferBuilder builder, Schale.FlatData.ParcelType rewardParcelType) { builder.AddInt(2, (int)rewardParcelType, 0); }
  public static void AddRewardParcelId(FlatBufferBuilder builder, long rewardParcelId) { builder.AddLong(3, rewardParcelId, 0); }
  public static void AddRewardParcelAmount(FlatBufferBuilder builder, long rewardParcelAmount) { builder.AddLong(4, rewardParcelAmount, 0); }
  public static Offset<Schale.FlatData.MiniGameRoadPuzzleAdditionalRewardExcel> EndMiniGameRoadPuzzleAdditionalRewardExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Schale.FlatData.MiniGameRoadPuzzleAdditionalRewardExcel>(o);
  }
  public MiniGameRoadPuzzleAdditionalRewardExcelT UnPack() {
    var _o = new MiniGameRoadPuzzleAdditionalRewardExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(MiniGameRoadPuzzleAdditionalRewardExcelT _o) {
		byte[] key = TableEncryptionService.CreateKey("MiniGameRoadPuzzleAdditionalReward");
    _o.EventContentId = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.EventContentId, key) : this.EventContentId;
    _o.UniqueId = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.UniqueId, key) : this.UniqueId;
    _o.RewardParcelType = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.RewardParcelType, key) : this.RewardParcelType;
    _o.RewardParcelId = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.RewardParcelId, key) : this.RewardParcelId;
    _o.RewardParcelAmount = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.RewardParcelAmount, key) : this.RewardParcelAmount;
  }
  public static Offset<Schale.FlatData.MiniGameRoadPuzzleAdditionalRewardExcel> Pack(FlatBufferBuilder builder, MiniGameRoadPuzzleAdditionalRewardExcelT _o) {
    if (_o == null) return default(Offset<Schale.FlatData.MiniGameRoadPuzzleAdditionalRewardExcel>);
    return CreateMiniGameRoadPuzzleAdditionalRewardExcel(
      builder,
      _o.EventContentId,
      _o.UniqueId,
      _o.RewardParcelType,
      _o.RewardParcelId,
      _o.RewardParcelAmount);
  }
}

public class MiniGameRoadPuzzleAdditionalRewardExcelT
{
  public long EventContentId { get; set; }
  public long UniqueId { get; set; }
  public Schale.FlatData.ParcelType RewardParcelType { get; set; }
  public long RewardParcelId { get; set; }
  public long RewardParcelAmount { get; set; }

  public MiniGameRoadPuzzleAdditionalRewardExcelT() {
    this.EventContentId = 0;
    this.UniqueId = 0;
    this.RewardParcelType = Schale.FlatData.ParcelType.None;
    this.RewardParcelId = 0;
    this.RewardParcelAmount = 0;
  }
}


static public class MiniGameRoadPuzzleAdditionalRewardExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*EventContentId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*UniqueId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*RewardParcelType*/, 4 /*Schale.FlatData.ParcelType*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*RewardParcelId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 12 /*RewardParcelAmount*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}



