// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

public enum MissionToastDisplayConditionType : int
{
  Always = 0,
  Complete = 1,
  Never = 2,
};


}



