// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Schale.Crypto;
using global::Google.FlatBuffers;

public struct ProductDailyRecordRewardExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ProductDailyRecordRewardExcel GetRootAsProductDailyRecordRewardExcel(ByteBuffer _bb) { return GetRootAsProductDailyRecordRewardExcel(_bb, new ProductDailyRecordRewardExcel()); }
  public static ProductDailyRecordRewardExcel GetRootAsProductDailyRecordRewardExcel(ByteBuffer _bb, ProductDailyRecordRewardExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ProductDailyRecordRewardExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int Day { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Schale.FlatData.ParcelType RewardParcelType(int j) { int o = __p.__offset(8); return o != 0 ? (Schale.FlatData.ParcelType)__p.bb.GetInt(__p.__vector(o) + j * 4) : (Schale.FlatData.ParcelType)0; }
  public int RewardParcelTypeLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<Schale.FlatData.ParcelType> GetRewardParcelTypeBytes() { return __p.__vector_as_span<Schale.FlatData.ParcelType>(8, 4); }
#else
  public ArraySegment<byte>? GetRewardParcelTypeBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public Schale.FlatData.ParcelType[] GetRewardParcelTypeArray() { int o = __p.__offset(8); if (o == 0) return null; int p = __p.__vector(o); int l = __p.__vector_len(o); Schale.FlatData.ParcelType[] a = new Schale.FlatData.ParcelType[l]; for (int i = 0; i < l; i++) { a[i] = (Schale.FlatData.ParcelType)__p.bb.GetInt(p + i * 4); } return a; }
  public long RewardId(int j) { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int RewardIdLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetRewardIdBytes() { return __p.__vector_as_span<long>(10, 8); }
#else
  public ArraySegment<byte>? GetRewardIdBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public long[] GetRewardIdArray() { return __p.__vector_as_array<long>(10); }
  public long RewardAmount(int j) { int o = __p.__offset(12); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int RewardAmountLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetRewardAmountBytes() { return __p.__vector_as_span<long>(12, 8); }
#else
  public ArraySegment<byte>? GetRewardAmountBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public long[] GetRewardAmountArray() { return __p.__vector_as_array<long>(12); }

  public static Offset<Schale.FlatData.ProductDailyRecordRewardExcel> CreateProductDailyRecordRewardExcel(FlatBufferBuilder builder,
      long Id = 0,
      int Day = 0,
      VectorOffset RewardParcelTypeOffset = default(VectorOffset),
      VectorOffset RewardIdOffset = default(VectorOffset),
      VectorOffset RewardAmountOffset = default(VectorOffset)) {
    builder.StartTable(5);
    ProductDailyRecordRewardExcel.AddId(builder, Id);
    ProductDailyRecordRewardExcel.AddRewardAmount(builder, RewardAmountOffset);
    ProductDailyRecordRewardExcel.AddRewardId(builder, RewardIdOffset);
    ProductDailyRecordRewardExcel.AddRewardParcelType(builder, RewardParcelTypeOffset);
    ProductDailyRecordRewardExcel.AddDay(builder, Day);
    return ProductDailyRecordRewardExcel.EndProductDailyRecordRewardExcel(builder);
  }

  public static void StartProductDailyRecordRewardExcel(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddId(FlatBufferBuilder builder, long id) { builder.AddLong(0, id, 0); }
  public static void AddDay(FlatBufferBuilder builder, int day) { builder.AddInt(1, day, 0); }
  public static void AddRewardParcelType(FlatBufferBuilder builder, VectorOffset rewardParcelTypeOffset) { builder.AddOffset(2, rewardParcelTypeOffset.Value, 0); }
  public static VectorOffset CreateRewardParcelTypeVector(FlatBufferBuilder builder, Schale.FlatData.ParcelType[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt((int)data[i]); return builder.EndVector(); }
  public static VectorOffset CreateRewardParcelTypeVectorBlock(FlatBufferBuilder builder, Schale.FlatData.ParcelType[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRewardParcelTypeVectorBlock(FlatBufferBuilder builder, ArraySegment<Schale.FlatData.ParcelType> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRewardParcelTypeVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Schale.FlatData.ParcelType>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartRewardParcelTypeVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddRewardId(FlatBufferBuilder builder, VectorOffset rewardIdOffset) { builder.AddOffset(3, rewardIdOffset.Value, 0); }
  public static VectorOffset CreateRewardIdVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateRewardIdVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRewardIdVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRewardIdVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartRewardIdVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static void AddRewardAmount(FlatBufferBuilder builder, VectorOffset rewardAmountOffset) { builder.AddOffset(4, rewardAmountOffset.Value, 0); }
  public static VectorOffset CreateRewardAmountVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateRewardAmountVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRewardAmountVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRewardAmountVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartRewardAmountVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static Offset<Schale.FlatData.ProductDailyRecordRewardExcel> EndProductDailyRecordRewardExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Schale.FlatData.ProductDailyRecordRewardExcel>(o);
  }
  public ProductDailyRecordRewardExcelT UnPack() {
    var _o = new ProductDailyRecordRewardExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ProductDailyRecordRewardExcelT _o) {
		byte[] key = TableEncryptionService.CreateKey("ProductDailyRecordReward");
    _o.Id = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.Id, key) : this.Id;
    _o.Day = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.Day, key) : this.Day;
    _o.RewardParcelType = new List<Schale.FlatData.ParcelType>();
    for (var _j = 0; _j < this.RewardParcelTypeLength; ++_j) {_o.RewardParcelType.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.RewardParcelType(_j), key) : this.RewardParcelType(_j));}
    _o.RewardId = new List<long>();
    for (var _j = 0; _j < this.RewardIdLength; ++_j) {_o.RewardId.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.RewardId(_j), key) : this.RewardId(_j));}
    _o.RewardAmount = new List<long>();
    for (var _j = 0; _j < this.RewardAmountLength; ++_j) {_o.RewardAmount.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.RewardAmount(_j), key) : this.RewardAmount(_j));}
  }
  public static Offset<Schale.FlatData.ProductDailyRecordRewardExcel> Pack(FlatBufferBuilder builder, ProductDailyRecordRewardExcelT _o) {
    if (_o == null) return default(Offset<Schale.FlatData.ProductDailyRecordRewardExcel>);
    var _RewardParcelType = default(VectorOffset);
    if (_o.RewardParcelType != null) {
      var __RewardParcelType = _o.RewardParcelType.ToArray();
      _RewardParcelType = CreateRewardParcelTypeVector(builder, __RewardParcelType);
    }
    var _RewardId = default(VectorOffset);
    if (_o.RewardId != null) {
      var __RewardId = _o.RewardId.ToArray();
      _RewardId = CreateRewardIdVector(builder, __RewardId);
    }
    var _RewardAmount = default(VectorOffset);
    if (_o.RewardAmount != null) {
      var __RewardAmount = _o.RewardAmount.ToArray();
      _RewardAmount = CreateRewardAmountVector(builder, __RewardAmount);
    }
    return CreateProductDailyRecordRewardExcel(
      builder,
      _o.Id,
      _o.Day,
      _RewardParcelType,
      _RewardId,
      _RewardAmount);
  }
}

public class ProductDailyRecordRewardExcelT
{
  public long Id { get; set; }
  public int Day { get; set; }
  public List<Schale.FlatData.ParcelType> RewardParcelType { get; set; }
  public List<long> RewardId { get; set; }
  public List<long> RewardAmount { get; set; }

  public ProductDailyRecordRewardExcelT() {
    this.Id = 0;
    this.Day = 0;
    this.RewardParcelType = null;
    this.RewardId = null;
    this.RewardAmount = null;
  }
}


static public class ProductDailyRecordRewardExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*Day*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 8 /*RewardParcelType*/, 4 /*Schale.FlatData.ParcelType*/, false)
      && verifier.VerifyVectorOfData(tablePos, 10 /*RewardId*/, 8 /*long*/, false)
      && verifier.VerifyVectorOfData(tablePos, 12 /*RewardAmount*/, 8 /*long*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}



