// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

public enum ProductSaleType : int
{
  Limited = 0,
  SaleDay = 1,
};


}



