// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Schale.Crypto;
using global::Google.FlatBuffers;

public struct ProductMonthlyExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ProductMonthlyExcel GetRootAsProductMonthlyExcel(ByteBuffer _bb) { return GetRootAsProductMonthlyExcel(_bb, new ProductMonthlyExcel()); }
  public static ProductMonthlyExcel GetRootAsProductMonthlyExcel(ByteBuffer _bb, ProductMonthlyExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ProductMonthlyExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string ProductId { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetProductIdBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetProductIdBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetProductIdArray() { return __p.__vector_as_array<byte>(6); }
  public string TeenProductId { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTeenProductIdBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetTeenProductIdBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetTeenProductIdArray() { return __p.__vector_as_array<byte>(8); }
  public Schale.FlatData.StoreType StoreType { get { int o = __p.__offset(10); return o != 0 ? (Schale.FlatData.StoreType)__p.bb.GetInt(o + __p.bb_pos) : Schale.FlatData.StoreType.None; } }
  public long Price { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string PriceReference { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPriceReferenceBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetPriceReferenceBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetPriceReferenceArray() { return __p.__vector_as_array<byte>(14); }
  public Schale.FlatData.ProductTagType ProductTagType { get { int o = __p.__offset(16); return o != 0 ? (Schale.FlatData.ProductTagType)__p.bb.GetInt(o + __p.bb_pos) : Schale.FlatData.ProductTagType.Monthly; } }
  public long MonthlyDays { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public bool UseMonthlyProductCheck { get { int o = __p.__offset(20); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public long PurchaseCountLimit { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public Schale.FlatData.ParcelType ParcelType(int j) { int o = __p.__offset(24); return o != 0 ? (Schale.FlatData.ParcelType)__p.bb.GetInt(__p.__vector(o) + j * 4) : (Schale.FlatData.ParcelType)0; }
  public int ParcelTypeLength { get { int o = __p.__offset(24); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<Schale.FlatData.ParcelType> GetParcelTypeBytes() { return __p.__vector_as_span<Schale.FlatData.ParcelType>(24, 4); }
#else
  public ArraySegment<byte>? GetParcelTypeBytes() { return __p.__vector_as_arraysegment(24); }
#endif
  public Schale.FlatData.ParcelType[] GetParcelTypeArray() { int o = __p.__offset(24); if (o == 0) return null; int p = __p.__vector(o); int l = __p.__vector_len(o); Schale.FlatData.ParcelType[] a = new Schale.FlatData.ParcelType[l]; for (int i = 0; i < l; i++) { a[i] = (Schale.FlatData.ParcelType)__p.bb.GetInt(p + i * 4); } return a; }
  public long ParcelId(int j) { int o = __p.__offset(26); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int ParcelIdLength { get { int o = __p.__offset(26); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetParcelIdBytes() { return __p.__vector_as_span<long>(26, 8); }
#else
  public ArraySegment<byte>? GetParcelIdBytes() { return __p.__vector_as_arraysegment(26); }
#endif
  public long[] GetParcelIdArray() { return __p.__vector_as_array<long>(26); }
  public long ParcelAmount(int j) { int o = __p.__offset(28); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int ParcelAmountLength { get { int o = __p.__offset(28); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetParcelAmountBytes() { return __p.__vector_as_span<long>(28, 8); }
#else
  public ArraySegment<byte>? GetParcelAmountBytes() { return __p.__vector_as_arraysegment(28); }
#endif
  public long[] GetParcelAmountArray() { return __p.__vector_as_array<long>(28); }
  public long EnterCostReduceGroupId { get { int o = __p.__offset(30); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public Schale.FlatData.ParcelType DailyParcelType(int j) { int o = __p.__offset(32); return o != 0 ? (Schale.FlatData.ParcelType)__p.bb.GetInt(__p.__vector(o) + j * 4) : (Schale.FlatData.ParcelType)0; }
  public int DailyParcelTypeLength { get { int o = __p.__offset(32); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<Schale.FlatData.ParcelType> GetDailyParcelTypeBytes() { return __p.__vector_as_span<Schale.FlatData.ParcelType>(32, 4); }
#else
  public ArraySegment<byte>? GetDailyParcelTypeBytes() { return __p.__vector_as_arraysegment(32); }
#endif
  public Schale.FlatData.ParcelType[] GetDailyParcelTypeArray() { int o = __p.__offset(32); if (o == 0) return null; int p = __p.__vector(o); int l = __p.__vector_len(o); Schale.FlatData.ParcelType[] a = new Schale.FlatData.ParcelType[l]; for (int i = 0; i < l; i++) { a[i] = (Schale.FlatData.ParcelType)__p.bb.GetInt(p + i * 4); } return a; }
  public long DailyParcelId(int j) { int o = __p.__offset(34); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int DailyParcelIdLength { get { int o = __p.__offset(34); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetDailyParcelIdBytes() { return __p.__vector_as_span<long>(34, 8); }
#else
  public ArraySegment<byte>? GetDailyParcelIdBytes() { return __p.__vector_as_arraysegment(34); }
#endif
  public long[] GetDailyParcelIdArray() { return __p.__vector_as_array<long>(34); }
  public long DailyParcelAmount(int j) { int o = __p.__offset(36); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int DailyParcelAmountLength { get { int o = __p.__offset(36); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetDailyParcelAmountBytes() { return __p.__vector_as_span<long>(36, 8); }
#else
  public ArraySegment<byte>? GetDailyParcelAmountBytes() { return __p.__vector_as_arraysegment(36); }
#endif
  public long[] GetDailyParcelAmountArray() { return __p.__vector_as_array<long>(36); }

  public static Offset<Schale.FlatData.ProductMonthlyExcel> CreateProductMonthlyExcel(FlatBufferBuilder builder,
      long Id = 0,
      StringOffset ProductIdOffset = default(StringOffset),
      StringOffset TeenProductIdOffset = default(StringOffset),
      Schale.FlatData.StoreType StoreType = Schale.FlatData.StoreType.None,
      long Price = 0,
      StringOffset PriceReferenceOffset = default(StringOffset),
      Schale.FlatData.ProductTagType ProductTagType = Schale.FlatData.ProductTagType.Monthly,
      long MonthlyDays = 0,
      bool UseMonthlyProductCheck = false,
      long PurchaseCountLimit = 0,
      VectorOffset ParcelTypeOffset = default(VectorOffset),
      VectorOffset ParcelIdOffset = default(VectorOffset),
      VectorOffset ParcelAmountOffset = default(VectorOffset),
      long EnterCostReduceGroupId = 0,
      VectorOffset DailyParcelTypeOffset = default(VectorOffset),
      VectorOffset DailyParcelIdOffset = default(VectorOffset),
      VectorOffset DailyParcelAmountOffset = default(VectorOffset)) {
    builder.StartTable(17);
    ProductMonthlyExcel.AddEnterCostReduceGroupId(builder, EnterCostReduceGroupId);
    ProductMonthlyExcel.AddPurchaseCountLimit(builder, PurchaseCountLimit);
    ProductMonthlyExcel.AddMonthlyDays(builder, MonthlyDays);
    ProductMonthlyExcel.AddPrice(builder, Price);
    ProductMonthlyExcel.AddId(builder, Id);
    ProductMonthlyExcel.AddDailyParcelAmount(builder, DailyParcelAmountOffset);
    ProductMonthlyExcel.AddDailyParcelId(builder, DailyParcelIdOffset);
    ProductMonthlyExcel.AddDailyParcelType(builder, DailyParcelTypeOffset);
    ProductMonthlyExcel.AddParcelAmount(builder, ParcelAmountOffset);
    ProductMonthlyExcel.AddParcelId(builder, ParcelIdOffset);
    ProductMonthlyExcel.AddParcelType(builder, ParcelTypeOffset);
    ProductMonthlyExcel.AddProductTagType(builder, ProductTagType);
    ProductMonthlyExcel.AddPriceReference(builder, PriceReferenceOffset);
    ProductMonthlyExcel.AddStoreType(builder, StoreType);
    ProductMonthlyExcel.AddTeenProductId(builder, TeenProductIdOffset);
    ProductMonthlyExcel.AddProductId(builder, ProductIdOffset);
    ProductMonthlyExcel.AddUseMonthlyProductCheck(builder, UseMonthlyProductCheck);
    return ProductMonthlyExcel.EndProductMonthlyExcel(builder);
  }

  public static void StartProductMonthlyExcel(FlatBufferBuilder builder) { builder.StartTable(17); }
  public static void AddId(FlatBufferBuilder builder, long id) { builder.AddLong(0, id, 0); }
  public static void AddProductId(FlatBufferBuilder builder, StringOffset productIdOffset) { builder.AddOffset(1, productIdOffset.Value, 0); }
  public static void AddTeenProductId(FlatBufferBuilder builder, StringOffset teenProductIdOffset) { builder.AddOffset(2, teenProductIdOffset.Value, 0); }
  public static void AddStoreType(FlatBufferBuilder builder, Schale.FlatData.StoreType storeType) { builder.AddInt(3, (int)storeType, 0); }
  public static void AddPrice(FlatBufferBuilder builder, long price) { builder.AddLong(4, price, 0); }
  public static void AddPriceReference(FlatBufferBuilder builder, StringOffset priceReferenceOffset) { builder.AddOffset(5, priceReferenceOffset.Value, 0); }
  public static void AddProductTagType(FlatBufferBuilder builder, Schale.FlatData.ProductTagType productTagType) { builder.AddInt(6, (int)productTagType, 0); }
  public static void AddMonthlyDays(FlatBufferBuilder builder, long monthlyDays) { builder.AddLong(7, monthlyDays, 0); }
  public static void AddUseMonthlyProductCheck(FlatBufferBuilder builder, bool useMonthlyProductCheck) { builder.AddBool(8, useMonthlyProductCheck, false); }
  public static void AddPurchaseCountLimit(FlatBufferBuilder builder, long purchaseCountLimit) { builder.AddLong(9, purchaseCountLimit, 0); }
  public static void AddParcelType(FlatBufferBuilder builder, VectorOffset parcelTypeOffset) { builder.AddOffset(10, parcelTypeOffset.Value, 0); }
  public static VectorOffset CreateParcelTypeVector(FlatBufferBuilder builder, Schale.FlatData.ParcelType[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt((int)data[i]); return builder.EndVector(); }
  public static VectorOffset CreateParcelTypeVectorBlock(FlatBufferBuilder builder, Schale.FlatData.ParcelType[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateParcelTypeVectorBlock(FlatBufferBuilder builder, ArraySegment<Schale.FlatData.ParcelType> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateParcelTypeVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Schale.FlatData.ParcelType>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartParcelTypeVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddParcelId(FlatBufferBuilder builder, VectorOffset parcelIdOffset) { builder.AddOffset(11, parcelIdOffset.Value, 0); }
  public static VectorOffset CreateParcelIdVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateParcelIdVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateParcelIdVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateParcelIdVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartParcelIdVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static void AddParcelAmount(FlatBufferBuilder builder, VectorOffset parcelAmountOffset) { builder.AddOffset(12, parcelAmountOffset.Value, 0); }
  public static VectorOffset CreateParcelAmountVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateParcelAmountVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateParcelAmountVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateParcelAmountVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartParcelAmountVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static void AddEnterCostReduceGroupId(FlatBufferBuilder builder, long enterCostReduceGroupId) { builder.AddLong(13, enterCostReduceGroupId, 0); }
  public static void AddDailyParcelType(FlatBufferBuilder builder, VectorOffset dailyParcelTypeOffset) { builder.AddOffset(14, dailyParcelTypeOffset.Value, 0); }
  public static VectorOffset CreateDailyParcelTypeVector(FlatBufferBuilder builder, Schale.FlatData.ParcelType[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt((int)data[i]); return builder.EndVector(); }
  public static VectorOffset CreateDailyParcelTypeVectorBlock(FlatBufferBuilder builder, Schale.FlatData.ParcelType[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDailyParcelTypeVectorBlock(FlatBufferBuilder builder, ArraySegment<Schale.FlatData.ParcelType> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDailyParcelTypeVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Schale.FlatData.ParcelType>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDailyParcelTypeVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddDailyParcelId(FlatBufferBuilder builder, VectorOffset dailyParcelIdOffset) { builder.AddOffset(15, dailyParcelIdOffset.Value, 0); }
  public static VectorOffset CreateDailyParcelIdVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateDailyParcelIdVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDailyParcelIdVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDailyParcelIdVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDailyParcelIdVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static void AddDailyParcelAmount(FlatBufferBuilder builder, VectorOffset dailyParcelAmountOffset) { builder.AddOffset(16, dailyParcelAmountOffset.Value, 0); }
  public static VectorOffset CreateDailyParcelAmountVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateDailyParcelAmountVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDailyParcelAmountVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDailyParcelAmountVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDailyParcelAmountVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static Offset<Schale.FlatData.ProductMonthlyExcel> EndProductMonthlyExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Schale.FlatData.ProductMonthlyExcel>(o);
  }
  public ProductMonthlyExcelT UnPack() {
    var _o = new ProductMonthlyExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ProductMonthlyExcelT _o) {
		byte[] key = TableEncryptionService.CreateKey("ProductMonthly");
    _o.Id = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.Id, key) : this.Id;
    _o.ProductId = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.ProductId, key) : this.ProductId;
    _o.TeenProductId = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.TeenProductId, key) : this.TeenProductId;
    _o.StoreType = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.StoreType, key) : this.StoreType;
    _o.Price = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.Price, key) : this.Price;
    _o.PriceReference = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.PriceReference, key) : this.PriceReference;
    _o.ProductTagType = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.ProductTagType, key) : this.ProductTagType;
    _o.MonthlyDays = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.MonthlyDays, key) : this.MonthlyDays;
    _o.UseMonthlyProductCheck = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.UseMonthlyProductCheck, key) : this.UseMonthlyProductCheck;
    _o.PurchaseCountLimit = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.PurchaseCountLimit, key) : this.PurchaseCountLimit;
    _o.ParcelType = new List<Schale.FlatData.ParcelType>();
    for (var _j = 0; _j < this.ParcelTypeLength; ++_j) {_o.ParcelType.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.ParcelType(_j), key) : this.ParcelType(_j));}
    _o.ParcelId = new List<long>();
    for (var _j = 0; _j < this.ParcelIdLength; ++_j) {_o.ParcelId.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.ParcelId(_j), key) : this.ParcelId(_j));}
    _o.ParcelAmount = new List<long>();
    for (var _j = 0; _j < this.ParcelAmountLength; ++_j) {_o.ParcelAmount.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.ParcelAmount(_j), key) : this.ParcelAmount(_j));}
    _o.EnterCostReduceGroupId = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.EnterCostReduceGroupId, key) : this.EnterCostReduceGroupId;
    _o.DailyParcelType = new List<Schale.FlatData.ParcelType>();
    for (var _j = 0; _j < this.DailyParcelTypeLength; ++_j) {_o.DailyParcelType.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.DailyParcelType(_j), key) : this.DailyParcelType(_j));}
    _o.DailyParcelId = new List<long>();
    for (var _j = 0; _j < this.DailyParcelIdLength; ++_j) {_o.DailyParcelId.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.DailyParcelId(_j), key) : this.DailyParcelId(_j));}
    _o.DailyParcelAmount = new List<long>();
    for (var _j = 0; _j < this.DailyParcelAmountLength; ++_j) {_o.DailyParcelAmount.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.DailyParcelAmount(_j), key) : this.DailyParcelAmount(_j));}
  }
  public static Offset<Schale.FlatData.ProductMonthlyExcel> Pack(FlatBufferBuilder builder, ProductMonthlyExcelT _o) {
    if (_o == null) return default(Offset<Schale.FlatData.ProductMonthlyExcel>);
    var _ProductId = _o.ProductId == null ? default(StringOffset) : builder.CreateString(_o.ProductId);
    var _TeenProductId = _o.TeenProductId == null ? default(StringOffset) : builder.CreateString(_o.TeenProductId);
    var _PriceReference = _o.PriceReference == null ? default(StringOffset) : builder.CreateString(_o.PriceReference);
    var _ParcelType = default(VectorOffset);
    if (_o.ParcelType != null) {
      var __ParcelType = _o.ParcelType.ToArray();
      _ParcelType = CreateParcelTypeVector(builder, __ParcelType);
    }
    var _ParcelId = default(VectorOffset);
    if (_o.ParcelId != null) {
      var __ParcelId = _o.ParcelId.ToArray();
      _ParcelId = CreateParcelIdVector(builder, __ParcelId);
    }
    var _ParcelAmount = default(VectorOffset);
    if (_o.ParcelAmount != null) {
      var __ParcelAmount = _o.ParcelAmount.ToArray();
      _ParcelAmount = CreateParcelAmountVector(builder, __ParcelAmount);
    }
    var _DailyParcelType = default(VectorOffset);
    if (_o.DailyParcelType != null) {
      var __DailyParcelType = _o.DailyParcelType.ToArray();
      _DailyParcelType = CreateDailyParcelTypeVector(builder, __DailyParcelType);
    }
    var _DailyParcelId = default(VectorOffset);
    if (_o.DailyParcelId != null) {
      var __DailyParcelId = _o.DailyParcelId.ToArray();
      _DailyParcelId = CreateDailyParcelIdVector(builder, __DailyParcelId);
    }
    var _DailyParcelAmount = default(VectorOffset);
    if (_o.DailyParcelAmount != null) {
      var __DailyParcelAmount = _o.DailyParcelAmount.ToArray();
      _DailyParcelAmount = CreateDailyParcelAmountVector(builder, __DailyParcelAmount);
    }
    return CreateProductMonthlyExcel(
      builder,
      _o.Id,
      _ProductId,
      _TeenProductId,
      _o.StoreType,
      _o.Price,
      _PriceReference,
      _o.ProductTagType,
      _o.MonthlyDays,
      _o.UseMonthlyProductCheck,
      _o.PurchaseCountLimit,
      _ParcelType,
      _ParcelId,
      _ParcelAmount,
      _o.EnterCostReduceGroupId,
      _DailyParcelType,
      _DailyParcelId,
      _DailyParcelAmount);
  }
}

public class ProductMonthlyExcelT
{
  public long Id { get; set; }
  public string ProductId { get; set; }
  public string TeenProductId { get; set; }
  public Schale.FlatData.StoreType StoreType { get; set; }
  public long Price { get; set; }
  public string PriceReference { get; set; }
  public Schale.FlatData.ProductTagType ProductTagType { get; set; }
  public long MonthlyDays { get; set; }
  public bool UseMonthlyProductCheck { get; set; }
  public long PurchaseCountLimit { get; set; }
  public List<Schale.FlatData.ParcelType> ParcelType { get; set; }
  public List<long> ParcelId { get; set; }
  public List<long> ParcelAmount { get; set; }
  public long EnterCostReduceGroupId { get; set; }
  public List<Schale.FlatData.ParcelType> DailyParcelType { get; set; }
  public List<long> DailyParcelId { get; set; }
  public List<long> DailyParcelAmount { get; set; }

  public ProductMonthlyExcelT() {
    this.Id = 0;
    this.ProductId = null;
    this.TeenProductId = null;
    this.StoreType = Schale.FlatData.StoreType.None;
    this.Price = 0;
    this.PriceReference = null;
    this.ProductTagType = Schale.FlatData.ProductTagType.Monthly;
    this.MonthlyDays = 0;
    this.UseMonthlyProductCheck = false;
    this.PurchaseCountLimit = 0;
    this.ParcelType = null;
    this.ParcelId = null;
    this.ParcelAmount = null;
    this.EnterCostReduceGroupId = 0;
    this.DailyParcelType = null;
    this.DailyParcelId = null;
    this.DailyParcelAmount = null;
  }
}


static public class ProductMonthlyExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 6 /*ProductId*/, false)
      && verifier.VerifyString(tablePos, 8 /*TeenProductId*/, false)
      && verifier.VerifyField(tablePos, 10 /*StoreType*/, 4 /*Schale.FlatData.StoreType*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Price*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 14 /*PriceReference*/, false)
      && verifier.VerifyField(tablePos, 16 /*ProductTagType*/, 4 /*Schale.FlatData.ProductTagType*/, 4, false)
      && verifier.VerifyField(tablePos, 18 /*MonthlyDays*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 20 /*UseMonthlyProductCheck*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 22 /*PurchaseCountLimit*/, 8 /*long*/, 8, false)
      && verifier.VerifyVectorOfData(tablePos, 24 /*ParcelType*/, 4 /*Schale.FlatData.ParcelType*/, false)
      && verifier.VerifyVectorOfData(tablePos, 26 /*ParcelId*/, 8 /*long*/, false)
      && verifier.VerifyVectorOfData(tablePos, 28 /*ParcelAmount*/, 8 /*long*/, false)
      && verifier.VerifyField(tablePos, 30 /*EnterCostReduceGroupId*/, 8 /*long*/, 8, false)
      && verifier.VerifyVectorOfData(tablePos, 32 /*DailyParcelType*/, 4 /*Schale.FlatData.ParcelType*/, false)
      && verifier.VerifyVectorOfData(tablePos, 34 /*DailyParcelId*/, 8 /*long*/, false)
      && verifier.VerifyVectorOfData(tablePos, 36 /*DailyParcelAmount*/, 8 /*long*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}



