// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

public enum ShopRefresherType : int
{
  None = 0,
  User = 1,
  Server = 2,
};


}



