// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Schale.Crypto;
using global::Google.FlatBuffers;

public struct ShopRecruitDirectingExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ShopRecruitDirectingExcel GetRootAsShopRecruitDirectingExcel(ByteBuffer _bb) { return GetRootAsShopRecruitDirectingExcel(_bb, new ShopRecruitDirectingExcel()); }
  public static ShopRecruitDirectingExcel GetRootAsShopRecruitDirectingExcel(ByteBuffer _bb, ShopRecruitDirectingExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ShopRecruitDirectingExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Path { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPathBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetPathBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetPathArray() { return __p.__vector_as_array<byte>(4); }
  public Schale.FlatData.GachaPhase Phase { get { int o = __p.__offset(6); return o != 0 ? (Schale.FlatData.GachaPhase)__p.bb.GetInt(o + __p.bb_pos) : Schale.FlatData.GachaPhase.GachaIntro; } }
  public int GachaAmount { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool IsSSR { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public Schale.FlatData.DirectingCharacter Character { get { int o = __p.__offset(12); return o != 0 ? (Schale.FlatData.DirectingCharacter)__p.bb.GetInt(o + __p.bb_pos) : Schale.FlatData.DirectingCharacter.None; } }

  public static Offset<Schale.FlatData.ShopRecruitDirectingExcel> CreateShopRecruitDirectingExcel(FlatBufferBuilder builder,
      StringOffset PathOffset = default(StringOffset),
      Schale.FlatData.GachaPhase Phase = Schale.FlatData.GachaPhase.GachaIntro,
      int GachaAmount = 0,
      bool IsSSR = false,
      Schale.FlatData.DirectingCharacter Character = Schale.FlatData.DirectingCharacter.None) {
    builder.StartTable(5);
    ShopRecruitDirectingExcel.AddCharacter(builder, Character);
    ShopRecruitDirectingExcel.AddGachaAmount(builder, GachaAmount);
    ShopRecruitDirectingExcel.AddPhase(builder, Phase);
    ShopRecruitDirectingExcel.AddPath(builder, PathOffset);
    ShopRecruitDirectingExcel.AddIsSSR(builder, IsSSR);
    return ShopRecruitDirectingExcel.EndShopRecruitDirectingExcel(builder);
  }

  public static void StartShopRecruitDirectingExcel(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddPath(FlatBufferBuilder builder, StringOffset pathOffset) { builder.AddOffset(0, pathOffset.Value, 0); }
  public static void AddPhase(FlatBufferBuilder builder, Schale.FlatData.GachaPhase phase) { builder.AddInt(1, (int)phase, 0); }
  public static void AddGachaAmount(FlatBufferBuilder builder, int gachaAmount) { builder.AddInt(2, gachaAmount, 0); }
  public static void AddIsSSR(FlatBufferBuilder builder, bool isSSR) { builder.AddBool(3, isSSR, false); }
  public static void AddCharacter(FlatBufferBuilder builder, Schale.FlatData.DirectingCharacter character) { builder.AddInt(4, (int)character, 0); }
  public static Offset<Schale.FlatData.ShopRecruitDirectingExcel> EndShopRecruitDirectingExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Schale.FlatData.ShopRecruitDirectingExcel>(o);
  }
  public ShopRecruitDirectingExcelT UnPack() {
    var _o = new ShopRecruitDirectingExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ShopRecruitDirectingExcelT _o) {
		byte[] key = TableEncryptionService.CreateKey("ShopRecruitDirecting");
    _o.Path = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.Path, key) : this.Path;
    _o.Phase = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.Phase, key) : this.Phase;
    _o.GachaAmount = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.GachaAmount, key) : this.GachaAmount;
    _o.IsSSR = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.IsSSR, key) : this.IsSSR;
    _o.Character = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.Character, key) : this.Character;
  }
  public static Offset<Schale.FlatData.ShopRecruitDirectingExcel> Pack(FlatBufferBuilder builder, ShopRecruitDirectingExcelT _o) {
    if (_o == null) return default(Offset<Schale.FlatData.ShopRecruitDirectingExcel>);
    var _Path = _o.Path == null ? default(StringOffset) : builder.CreateString(_o.Path);
    return CreateShopRecruitDirectingExcel(
      builder,
      _Path,
      _o.Phase,
      _o.GachaAmount,
      _o.IsSSR,
      _o.Character);
  }
}

public class ShopRecruitDirectingExcelT
{
  public string Path { get; set; }
  public Schale.FlatData.GachaPhase Phase { get; set; }
  public int GachaAmount { get; set; }
  public bool IsSSR { get; set; }
  public Schale.FlatData.DirectingCharacter Character { get; set; }

  public ShopRecruitDirectingExcelT() {
    this.Path = null;
    this.Phase = Schale.FlatData.GachaPhase.GachaIntro;
    this.GachaAmount = 0;
    this.IsSSR = false;
    this.Character = Schale.FlatData.DirectingCharacter.None;
  }
}


static public class ShopRecruitDirectingExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Path*/, false)
      && verifier.VerifyField(tablePos, 6 /*Phase*/, 4 /*Schale.FlatData.GachaPhase*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*GachaAmount*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*IsSSR*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 12 /*Character*/, 4 /*Schale.FlatData.DirectingCharacter*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}



