// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

public enum SkillSlotHighLightType : int
{
  None = 0,
  New = 1,
  Upgrade = 2,
};


}



