// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

public enum StrategyEnvironment : int
{
  None = 0,
  MapFog = 1,
};


}



