// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Schale.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Schale.Crypto;
using global::Google.FlatBuffers;

public struct TranscendenceRecipeExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static TranscendenceRecipeExcel GetRootAsTranscendenceRecipeExcel(ByteBuffer _bb) { return GetRootAsTranscendenceRecipeExcel(_bb, new TranscendenceRecipeExcel()); }
  public static TranscendenceRecipeExcel GetRootAsTranscendenceRecipeExcel(ByteBuffer _bb, TranscendenceRecipeExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TranscendenceRecipeExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string DevName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDevNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetDevNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDevNameArray() { return __p.__vector_as_array<byte>(6); }
  public Schale.FlatData.CurrencyTypes CostCurrencyType { get { int o = __p.__offset(8); return o != 0 ? (Schale.FlatData.CurrencyTypes)__p.bb.GetInt(o + __p.bb_pos) : Schale.FlatData.CurrencyTypes.Invalid; } }
  public long CostCurrencyAmount { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public Schale.FlatData.ParcelType ParcelType(int j) { int o = __p.__offset(12); return o != 0 ? (Schale.FlatData.ParcelType)__p.bb.GetInt(__p.__vector(o) + j * 4) : (Schale.FlatData.ParcelType)0; }
  public int ParcelTypeLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<Schale.FlatData.ParcelType> GetParcelTypeBytes() { return __p.__vector_as_span<Schale.FlatData.ParcelType>(12, 4); }
#else
  public ArraySegment<byte>? GetParcelTypeBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public Schale.FlatData.ParcelType[] GetParcelTypeArray() { int o = __p.__offset(12); if (o == 0) return null; int p = __p.__vector(o); int l = __p.__vector_len(o); Schale.FlatData.ParcelType[] a = new Schale.FlatData.ParcelType[l]; for (int i = 0; i < l; i++) { a[i] = (Schale.FlatData.ParcelType)__p.bb.GetInt(p + i * 4); } return a; }
  public long ParcelId(int j) { int o = __p.__offset(14); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int ParcelIdLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetParcelIdBytes() { return __p.__vector_as_span<long>(14, 8); }
#else
  public ArraySegment<byte>? GetParcelIdBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public long[] GetParcelIdArray() { return __p.__vector_as_array<long>(14); }
  public int ParcelAmount(int j) { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int ParcelAmountLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetParcelAmountBytes() { return __p.__vector_as_span<int>(16, 4); }
#else
  public ArraySegment<byte>? GetParcelAmountBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public int[] GetParcelAmountArray() { return __p.__vector_as_array<int>(16); }

  public static Offset<Schale.FlatData.TranscendenceRecipeExcel> CreateTranscendenceRecipeExcel(FlatBufferBuilder builder,
      long Id = 0,
      StringOffset DevNameOffset = default(StringOffset),
      Schale.FlatData.CurrencyTypes CostCurrencyType = Schale.FlatData.CurrencyTypes.Invalid,
      long CostCurrencyAmount = 0,
      VectorOffset ParcelTypeOffset = default(VectorOffset),
      VectorOffset ParcelIdOffset = default(VectorOffset),
      VectorOffset ParcelAmountOffset = default(VectorOffset)) {
    builder.StartTable(7);
    TranscendenceRecipeExcel.AddCostCurrencyAmount(builder, CostCurrencyAmount);
    TranscendenceRecipeExcel.AddId(builder, Id);
    TranscendenceRecipeExcel.AddParcelAmount(builder, ParcelAmountOffset);
    TranscendenceRecipeExcel.AddParcelId(builder, ParcelIdOffset);
    TranscendenceRecipeExcel.AddParcelType(builder, ParcelTypeOffset);
    TranscendenceRecipeExcel.AddCostCurrencyType(builder, CostCurrencyType);
    TranscendenceRecipeExcel.AddDevName(builder, DevNameOffset);
    return TranscendenceRecipeExcel.EndTranscendenceRecipeExcel(builder);
  }

  public static void StartTranscendenceRecipeExcel(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddId(FlatBufferBuilder builder, long id) { builder.AddLong(0, id, 0); }
  public static void AddDevName(FlatBufferBuilder builder, StringOffset devNameOffset) { builder.AddOffset(1, devNameOffset.Value, 0); }
  public static void AddCostCurrencyType(FlatBufferBuilder builder, Schale.FlatData.CurrencyTypes costCurrencyType) { builder.AddInt(2, (int)costCurrencyType, 0); }
  public static void AddCostCurrencyAmount(FlatBufferBuilder builder, long costCurrencyAmount) { builder.AddLong(3, costCurrencyAmount, 0); }
  public static void AddParcelType(FlatBufferBuilder builder, VectorOffset parcelTypeOffset) { builder.AddOffset(4, parcelTypeOffset.Value, 0); }
  public static VectorOffset CreateParcelTypeVector(FlatBufferBuilder builder, Schale.FlatData.ParcelType[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt((int)data[i]); return builder.EndVector(); }
  public static VectorOffset CreateParcelTypeVectorBlock(FlatBufferBuilder builder, Schale.FlatData.ParcelType[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateParcelTypeVectorBlock(FlatBufferBuilder builder, ArraySegment<Schale.FlatData.ParcelType> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateParcelTypeVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Schale.FlatData.ParcelType>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartParcelTypeVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddParcelId(FlatBufferBuilder builder, VectorOffset parcelIdOffset) { builder.AddOffset(5, parcelIdOffset.Value, 0); }
  public static VectorOffset CreateParcelIdVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateParcelIdVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateParcelIdVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateParcelIdVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartParcelIdVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static void AddParcelAmount(FlatBufferBuilder builder, VectorOffset parcelAmountOffset) { builder.AddOffset(6, parcelAmountOffset.Value, 0); }
  public static VectorOffset CreateParcelAmountVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateParcelAmountVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateParcelAmountVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateParcelAmountVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartParcelAmountVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Schale.FlatData.TranscendenceRecipeExcel> EndTranscendenceRecipeExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Schale.FlatData.TranscendenceRecipeExcel>(o);
  }
  public TranscendenceRecipeExcelT UnPack() {
    var _o = new TranscendenceRecipeExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TranscendenceRecipeExcelT _o) {
		byte[] key = TableEncryptionService.CreateKey("TranscendenceRecipe");
    _o.Id = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.Id, key) : this.Id;
    _o.DevName = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.DevName, key) : this.DevName;
    _o.CostCurrencyType = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.CostCurrencyType, key) : this.CostCurrencyType;
    _o.CostCurrencyAmount = TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.CostCurrencyAmount, key) : this.CostCurrencyAmount;
    _o.ParcelType = new List<Schale.FlatData.ParcelType>();
    for (var _j = 0; _j < this.ParcelTypeLength; ++_j) {_o.ParcelType.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.ParcelType(_j), key) : this.ParcelType(_j));}
    _o.ParcelId = new List<long>();
    for (var _j = 0; _j < this.ParcelIdLength; ++_j) {_o.ParcelId.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.ParcelId(_j), key) : this.ParcelId(_j));}
    _o.ParcelAmount = new List<int>();
    for (var _j = 0; _j < this.ParcelAmountLength; ++_j) {_o.ParcelAmount.Add(TableEncryptionService.UseEncryption ? TableEncryptionService.Convert(this.ParcelAmount(_j), key) : this.ParcelAmount(_j));}
  }
  public static Offset<Schale.FlatData.TranscendenceRecipeExcel> Pack(FlatBufferBuilder builder, TranscendenceRecipeExcelT _o) {
    if (_o == null) return default(Offset<Schale.FlatData.TranscendenceRecipeExcel>);
    var _DevName = _o.DevName == null ? default(StringOffset) : builder.CreateString(_o.DevName);
    var _ParcelType = default(VectorOffset);
    if (_o.ParcelType != null) {
      var __ParcelType = _o.ParcelType.ToArray();
      _ParcelType = CreateParcelTypeVector(builder, __ParcelType);
    }
    var _ParcelId = default(VectorOffset);
    if (_o.ParcelId != null) {
      var __ParcelId = _o.ParcelId.ToArray();
      _ParcelId = CreateParcelIdVector(builder, __ParcelId);
    }
    var _ParcelAmount = default(VectorOffset);
    if (_o.ParcelAmount != null) {
      var __ParcelAmount = _o.ParcelAmount.ToArray();
      _ParcelAmount = CreateParcelAmountVector(builder, __ParcelAmount);
    }
    return CreateTranscendenceRecipeExcel(
      builder,
      _o.Id,
      _DevName,
      _o.CostCurrencyType,
      _o.CostCurrencyAmount,
      _ParcelType,
      _ParcelId,
      _ParcelAmount);
  }
}

public class TranscendenceRecipeExcelT
{
  public long Id { get; set; }
  public string DevName { get; set; }
  public Schale.FlatData.CurrencyTypes CostCurrencyType { get; set; }
  public long CostCurrencyAmount { get; set; }
  public List<Schale.FlatData.ParcelType> ParcelType { get; set; }
  public List<long> ParcelId { get; set; }
  public List<int> ParcelAmount { get; set; }

  public TranscendenceRecipeExcelT() {
    this.Id = 0;
    this.DevName = null;
    this.CostCurrencyType = Schale.FlatData.CurrencyTypes.Invalid;
    this.CostCurrencyAmount = 0;
    this.ParcelType = null;
    this.ParcelId = null;
    this.ParcelAmount = null;
  }
}


static public class TranscendenceRecipeExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 6 /*DevName*/, false)
      && verifier.VerifyField(tablePos, 8 /*CostCurrencyType*/, 4 /*Schale.FlatData.CurrencyTypes*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*CostCurrencyAmount*/, 8 /*long*/, 8, false)
      && verifier.VerifyVectorOfData(tablePos, 12 /*ParcelType*/, 4 /*Schale.FlatData.ParcelType*/, false)
      && verifier.VerifyVectorOfData(tablePos, 14 /*ParcelId*/, 8 /*long*/, false)
      && verifier.VerifyVectorOfData(tablePos, 16 /*ParcelAmount*/, 4 /*int*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}



